---
- hosts: all
  become: true
  tasks:
    #Changing Script Ownership
    - name: Change ownership of Script
      copy:
        src: /home/vagrant/Exam_Project/LAMP_stack.sh
        dest: /home/vagrant/LAMP_stack.sh
        mode: "0775"
    #Installing LAMP stack
    - name: install LAMP stack with bash script
      tags: ubuntu, LAMP, php, mySQL
      shell: ./LAMP_stack.sh
    #Checking if PHP application is accessible
    - name: Check PHP application accessibility
      uri:
        url: http://192.168.56.27
      register: php_out
      ignore_errors: true

    - name: Display message if PHP application is accessible
      debug:
        msg: "PHP application is accessible"
      when: php_out.status == 200

      #Cronjob to check server uptime at 12am
    - name: Add cron Job for uptime check
      cron:
        name: "Check server Uptime Check"
        minute: "0"
        hour: "0"
        job: "uptime >> /var/log/server_uptime.log"

    - name: Notify user
      shell: echo "server uptime is save in /var/log/server_uptime.log"
